# Generated by Django 5.0.2 on 2024-04-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_categoria"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cafe",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=20)),
                ("preco", models.DecimalField(decimal_places=2, max_digits=4)),
                ("descricao", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Doce",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=20)),
                ("preco", models.DecimalField(decimal_places=2, max_digits=4)),
                ("descricao", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Salgado",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=20)),
                ("preco", models.DecimalField(decimal_places=2, max_digits=4)),
                ("descricao", models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name="Categoria",
        ),
    ]
